# Generated by Django 4.0.5 on 2022-06-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pictures')),
                ('disc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='whyus',
            name='iamge',
        ),
        migrations.AddField(
            model_name='whyus',
            name='image',
            field=models.ImageField(default=23, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
