# Generated by Django 4.0.5 on 2022-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_team_remove_whyus_iamge_whyus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='disc',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
